//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cricketer
    {
        public int Jersey_Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Player_Role { get; set; }
        public string Contract_Category { get; set; }
    }
}
